=== imhogan/RESTFetcher/Schemas/RestFetcherCommands.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://THINKronicity.com.au/Schemas/Smirnov/RestFetcherCommands.xsd"
  xmlns="http://THINKronicity.com.au/Schemas/Smirnov/RestFetcherCommands.xsd">
  <!-- 
    Schema for RESTFetcher Command & actions file and Lambda Event Maps.
    
    Author Ian Hogan, Ian_MacDonald_Hogan@yahoo.com  
    -->
  <xs:element name="LambdaEventMaps">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="LambdaEvent"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="LambdaEvent">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="MatchKey"/>
      </xs:sequence>
      <xs:attribute name="Event" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="MatchKey">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="RegExp"/>
        <xs:element ref="Parameters" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="Command" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Commands">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Command"/>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="CommandNameKey">
      <xs:selector xpath="Command"/>
      <xs:field xpath="@Name"/>
    </xs:key>
    <xs:keyref name="CommandNameKeyRef" refer="CommandNameKey">
      <xs:selector xpath=".//Action"/>
      <xs:field xpath="@Command"/>
    </xs:keyref>
  </xs:element>
  <xs:simpleType name="ActionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Command"/>
      <xs:enumeration value="Output"/>
      <xs:enumeration value="XSLT"/>
      <xs:enumeration value="XSLT2"/>
      <xs:enumeration value="FOP"/>
      <xs:enumeration value="eMail"/>
      <xs:enumeration value="S3PUT"/>
      <xs:enumeration value="S3DELETE"/>
      <xs:enumeration value="AddResult"/>
      <xs:enumeration value="ZIP"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="HeaderType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="BasicAuth"/>
      <xs:enumeration value="AuthToken"/>
      <xs:enumeration value="Text"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ParameterFormatType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Path"/>
      <xs:enumeration value="Query"/>
      <xs:enumeration value="Form"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="BodyType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ActionContent"/>
      <xs:enumeration value="Template"/>
      <xs:enumeration value="Form"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="Command">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Endpoint" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="Headers" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="Parameters" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="Body" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="Actions" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="IsInit" type="xs:boolean"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
      <xs:attribute name="IsJSON" type="xs:boolean"/>
      <xs:attribute name="UseJSON2SafeXML" type="xs:boolean"/>
      <!-- TODO: Add verb types -->
      <xs:attribute name="Verb"/>
      <xs:attribute name="Timeout" type="xs:integer"/>
      <xs:attribute name="IsNOP" type="xs:boolean"/>
      <xs:attribute name="NoResultBody" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Headers">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Header"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Header">
    <xs:complexType mixed="true">
      <xs:attribute name="Comment"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
      <xs:attribute name="XPath"/>
      <xs:attribute name="Function"/>
      <xs:attribute name="Type" type="HeaderType"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Parameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Parameter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Parameter">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="RegExp" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="Comment"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
      <xs:attribute name="Separator"/>
      <xs:attribute name="Format" type="ParameterFormatType"/>
      <xs:attribute name="XPath"/>
      <xs:attribute name="Function"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Body">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="Actions" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="Comment"/>
      <xs:attribute name="Type" type="BodyType"/>
      <xs:attribute name="ContentType"/>
      <xs:attribute name="XPath"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Actions">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Action"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Action">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded" minOccurs="0">
        <xs:element ref="Parameters" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="Body" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="Actions" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="Command" type="xs:NCName"/>
      <xs:attribute name="Match"/>
      <xs:attribute name="Mode"/>
      <xs:attribute name="Root" type="xs:NCName"/>
      <xs:attribute name="Transform" type="xs:NCName"/>
      <xs:attribute name="Type" use="required" type="ActionType"/>
      <xs:attribute name="ParametersRegExp"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== imhogan/RESTFetcher/Samples/SurveyMonkey/S3Buckets/files/config/TestSurveyMonkeyProcessing.xml
<Commands 
	xmlns="http://THINKronicity.com.au/Schemas/Smirnov/RestFetcherCommands.xsd" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://THINKronicity.com.au/Schemas/Smirnov/RestFetcherCommands.xsd http://thinkronicity.com.au/Schemas/RestFetcherCommands.xsd"
	>
	<!-- 
		Sample RESTFetcher commands file for Survey Monkey API V3 processing.
		
		Author Ian Hogan, Ian.Hogan@THINKronicity.com.au
	-->
	<Command Name="DoNothing" IsNOP="true">
		<Actions>
			<Action Type="AddResult">
				<Parameters>
					<Parameter Name="Result">Did nothing!</Parameter>
				</Parameters>
			</Action>
		</Actions>
	</Command>
	<Command Name="GetSurveyList" Timeout="5000" IsJSON="true">
		<Headers>
			<Header Name="Authorization" Type="AuthToken">$authToken</Header>
		</Headers>
		<Parameters>
			<Parameter Name="Resource">surveys</Parameter>
			<Parameter Name="api_key" Separator="?" Format="Query">$API_Key</Parameter>
		</Parameters>
		<Actions>
			<Action Type="S3PUT" Mode="debug">
				<Parameters>
					<Parameter Name="Bucket">$S3_Bucket</Parameter>
					<Parameter Name="Name">=${REST_Log_Path}/surveys_${TestID}.xml</Parameter>
				</Parameters>
			</Action>
			<Action Type="FOP">
				<Parameters>
					<Parameter Name="Transform" Function="S3URL">=${S3_Bucket},xsl/TestSurveysList2FO.xsl</Parameter>
					<Parameter Name="Bucket">$S3_Bucket</Parameter>
					<Parameter Name="Name">=PDFs/${TestID}.pdf</Parameter>
				</Parameters>
			</Action>
			<Action Type="eMail">
				<Parameters>
					<Parameter Name="From">$EmailSender</Parameter>
					<Parameter Name="Name">$EmailSenderName</Parameter>
					<Parameter Name="To">$EmailSender</Parameter>
					<Parameter Name="Subject">=Here is the survey list.</Parameter>
					<Parameter Name="Attachments" Function="S3URL">=${S3_Bucket},PDFs/${TestID}.pdf</Parameter>
				</Parameters>
				<Body ContentType="text/html"><![CDATA[=<html><body><p>Hi, here is the PDF from ${S3_Bucket}/PDFs/${TestID}.pdf</p><br/><p>Enjoy!</p></body></html>]]>
				</Body>
				<Actions>
					<Action Type="AddResult" ParametersRegExp="^EmailResult$">
						<Parameters>
							<Parameter Name="EmailResult">=Survey List sent to ${EmailSender}</Parameter>
						</Parameters>
					</Action>
					<Action Type="S3DELETE" Mode="!debug">
						<Parameters>
							<Parameter Name="Bucket">$S3_Bucket</Parameter>
							<Parameter Name="Name">=PDFs/${TestID}.pdf</Parameter>
						</Parameters>
					</Action>
				</Actions>
			</Action>
		</Actions>
	</Command>
	<Command Name="GetAllSurveys" Timeout="5000" IsJSON="true">
		<Headers>
			<Header Name="Authorization" Type="AuthToken">$authToken</Header>
		</Headers>
		<Parameters>
			<Parameter Name="Resource">surveys</Parameter>
			<Parameter Name="api_key" Separator="?" Format="Query">$API_Key</Parameter>
		</Parameters>
		<Actions>
			<Action Type="S3PUT" Mode="debug">
				<Parameters>
					<Parameter Name="Bucket">$S3_Bucket</Parameter>
					<Parameter Name="Name">=${REST_Log_Path}/Surveys_List_${TestID}.xml</Parameter>
				</Parameters>
			</Action>
			<Action Type="Command" Command="GetSurveyDetails" Match="//data/id" Root="Surveys">
				<Parameters>
					<Parameter Name="SurveyID" XPath="."/>
				</Parameters>
				<Actions>
					<Action Type="S3PUT">
						<Parameters>
							<Parameter Name="Bucket">$S3_Bucket</Parameter>
							<Parameter Name="Name">=config/AllSurveyDetails_${TestID}.xml</Parameter>
						</Parameters>
					</Action>
					<Action Type="eMail">
						<Parameters>
							<Parameter Name="From">$EmailSender</Parameter>
							<Parameter Name="Name">$EmailSenderName</Parameter>
							<Parameter Name="To">$EmailSender</Parameter>
							<Parameter Name="Subject">=Here is the survey details XML file.</Parameter>
							<Parameter Name="Attachments" Function="S3URL">=${S3_Bucket},config/AllSurveyDetails_${TestID}.xml</Parameter>
						</Parameters>
						<Body ContentType="text/html"><![CDATA[=<html><body><p>Hi, here is the detail of all surveys in XML format - the file is also stored in S3://${S3_Bucket}/config/AllSurveyDetails_${TestID}.xml</p><br/><p>Enjoy!</p></body></html>]]>
						</Body>
						<Actions>
							<Action Type="AddResult" ParametersRegExp="^EmailResult$">
								<Parameters>
									<Parameter Name="EmailResult">=Survey details XML sent to ${EmailSender}</Parameter>
								</Parameters>
							</Action>
						</Actions>
					</Action>
				</Actions>
			</Action>
		</Actions>
	</Command>
	<Command Name="GetSurveyDetails" Timeout="5000" IsJSON="true">
		<Headers>
			<Header Name="Authorization" Type="AuthToken">$authToken</Header>
		</Headers>
		<Parameters>
			<Parameter Name="Resource">surveys</Parameter>
			<Parameter Name="ID">$SurveyID</Parameter>
			<Parameter Name="Aspect">details</Parameter>
			<Parameter Name="api_key" Separator="?" Format="Query">$API_Key</Parameter>
		</Parameters>
		<Actions>
			<Action Type="S3PUT" Mode="debug">
				<Parameters>
					<Parameter Name="Bucket">$S3_Bucket</Parameter>
					<Parameter Name="Name">=${REST_Log_Path}/Survey_${SurveyID}_Details_${TestID}.xml</Parameter>
				</Parameters>
			</Action>
		</Actions>
	</Command>
</Commands>
